### PR TITLE
Official Chromecast Backgrounds, Screen Size Enhancements, and Custom Device Naming

### PR DESCRIPTION
**Pull request by ProfessorAnomaly**
Just a few enhancements to the server.

### CODE REVIEW

**Comment by ProfessorAnomaly** [comment]
Let me know if there is anything wrong with the changes and if you need help with furthur updates.

**Comment by anthonywebb** [comment]
Might be off topic, but what OS/version are you able to run this project under?  I have a mac with the latest node and the project isnt working.

**Comment by ProfessorAnomaly** [comment]
I've been successful in running this under Ubuntu and Windows 8.

**Comment by mauimauer** [comment]
What about the license of those background pics?

**Comment by geekgonecrazy** [comment]
@anthonywebb I'm on mac and it is working.  Did npm successfully install all dependancies?

**Comment by ProfessorAnomaly** [comment]
The background pictures should be under the creative free license.

**Pull request merged**
